[package]
name = "tarsum"
version = "0.1.0"
authors = ["Paweł Żuk <pzuk@0x04.net>"]
edition = "2018"

[dependencies]
bzip2 = "0.4"
clap = "2.33.3"
flate2 = "1.0.19"
sha2 = "0.9.2"
xz2 = "0.1.6"
tar = "0.4.3"